/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gamesupply.swing;

import com.gamesupply.controller.ProductController;
import com.gamesupply.controller.StockController;
import com.gamesupply.dto.StockDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author cuestas
 */
public class MaintainStock extends javax.swing.JInternalFrame {

    /**
     * Creates new form MaintainStock
     */
    
    private List<StockDTO> stockList = new ArrayList<StockDTO>();
//    private List<StockDTO> stockFilialList = new ArrayList<StockDTO>();
    private StockDTO stock = new StockDTO();
    private String branch1Qty;
    private String branch2Qty;
    private String branch3Qty;
    private String store;
    private StockDTO selectedStockDTO;
//    private String actualBranchQty = "";

    public MaintainStock(String store) {
            
        this.store = store;
        getBranchStock(store);
        initComponents();
        fieldQtyBranch1.setVisible(false);
        fieldQtyBranch2.setVisible(false);
        fieldQtyBranch3.setVisible(false);
        selecttedProductId.setVisible(false);
        
//        selectBranch(store);
    }   
//    private void selectBranch(String store){
//        
//        
//            
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        selectedBranchQuantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fieldQtyBranch1 = new javax.swing.JTextField();
        fieldQtyBranch3 = new javax.swing.JTextField();
        fieldQtyBranch2 = new javax.swing.JTextField();
        selecttedProductId = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Controle de Estoque");

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${stockList}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${platform}"));
        columnBinding.setColumnName("Platform");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${type}"));
        columnBinding.setColumnName("Type");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${branchQuantity}"));
        columnBinding.setColumnName("Branch Quantity");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${selectedStockDTO}"), jTable1, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTable1ComponentHidden(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Quantidade");

        selectedBranchQuantity.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selectedBranchQuantityPropertyChange(evt);
            }
        });

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.branch1}"), fieldQtyBranch1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        fieldQtyBranch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQtyBranch1ActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.branch3}"), fieldQtyBranch3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        fieldQtyBranch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQtyBranch3ActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.branch2}"), fieldQtyBranch2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        fieldQtyBranch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQtyBranch2ActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idProduct}"), selecttedProductId, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        selecttedProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecttedProductIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldQtyBranch1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldQtyBranch2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldQtyBranch3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selecttedProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedBranchQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(selectedBranchQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldQtyBranch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldQtyBranch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldQtyBranch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecttedProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
//        StockDTO stockDTO = new StockDTO();
        
        this.selectedStockDTO.setIdProduct(Integer.parseInt(selecttedProductId.getText()));
        
        if(this.store.toUpperCase().endsWith("A")){
            this.selectedStockDTO.setBranch1(this.selectedStockDTO.getBranch1() + Integer.parseInt(selectedBranchQuantity.getText()));
        }
        if(this.store.toUpperCase().endsWith("B")){
            this.selectedStockDTO.setBranch2(this.selectedStockDTO.getBranch2() + Integer.parseInt(selectedBranchQuantity.getText()));
        }
        if(this.store.toUpperCase().endsWith("C")){
            this.selectedStockDTO.setBranch3(this.selectedStockDTO.getBranch3() + Integer.parseInt(selectedBranchQuantity.getText()));
        }
        
        StockController.updateStock(this.selectedStockDTO);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldQtyBranch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQtyBranch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQtyBranch1ActionPerformed

    private void fieldQtyBranch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQtyBranch3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQtyBranch3ActionPerformed

    private void fieldQtyBranch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQtyBranch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQtyBranch2ActionPerformed

    private void selectedBranchQuantityPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selectedBranchQuantityPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedBranchQuantityPropertyChange

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
//        this.selectedBranchQuantity.setText(branch1Qty);
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
                
        if(this.store.toUpperCase().endsWith("A")){
            selectedBranchQuantity.setText(fieldQtyBranch1.getText());
        }
        if(this.store.toUpperCase().endsWith("B")){
             selectedBranchQuantity.setText(fieldQtyBranch2.getText());
        }
        if(this.store.toUpperCase().endsWith("C")){
             selectedBranchQuantity.setText(fieldQtyBranch3.getText());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void selecttedProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecttedProductIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecttedProductIdActionPerformed

    private void jTable1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentHidden

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldQtyBranch1;
    private javax.swing.JTextField fieldQtyBranch2;
    private javax.swing.JTextField fieldQtyBranch3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField selectedBranchQuantity;
    private javax.swing.JTextField selecttedProductId;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

   
    
//    public List<StockDTO> getStockFilialList() {
//        return stockFilialList;
//    }
//
//    public void setStockFilialList(List<StockDTO> stockFilialList) {
//        this.stockFilialList = stockFilialList;
//    }
    
    

    public List<StockDTO> getStockList() {
        return stockList;
    }

    public void setStockList(List<StockDTO> stockList) {
        this.stockList = stockList;
    }

    public StockDTO getStock() {
        return stock;
    }

    public void setStock(StockDTO stock) {
        this.stock = stock;
    }

    public String getBranch1Qty() {
        return branch1Qty;
    }

    public void setBranch1Qty(String branch1Qty) {
        this.branch1Qty = branch1Qty;
    }

    public String getBranch2Qty() {
        return branch2Qty;
    }

    public void setBranch2Qty(String branch2Qty) {
        this.branch2Qty = branch2Qty;
    }

    public String getBranch3Qty() {
        return branch3Qty;
    }

    public void setBranch3Qty(String branch3Qty) {
        this.branch3Qty = branch3Qty;
    }

    public StockDTO getSelectedStockDTO() {
        return selectedStockDTO;
    }

    public void setSelectedStockDTO(StockDTO selectedStockDTO) {
        this.selectedStockDTO = selectedStockDTO;
    }

    private void getBranchStock(String store) {
        List<StockDTO> tmpStock = StockController.findall();
        
        for(StockDTO stockTmp : tmpStock){
            StockDTO stockDTO = new StockDTO();
            
            
            stockDTO.setBranch1(stockTmp.getBranch1());
            stockDTO.setBranch2(stockTmp.getBranch2());
            stockDTO.setBranch3(stockTmp.getBranch3());
            stockDTO.setDescription(stockTmp.getDescription());
            stockDTO.setGenre(stockTmp.getGenre());
            stockDTO.setIdProduct(stockTmp.getIdProduct());
            stockDTO.setName(stockTmp.getName());
            stockDTO.setPlatform(stockTmp.getPlatform());
            stockDTO.setPrice(stockTmp.getPrice());
            stockDTO.setType(stockTmp.getType());
            
            if(store.endsWith("A")){
                stockDTO.setBranchQuantity(stockTmp.getBranch1());
            }
            
            if(store.endsWith("B")){
                stockDTO.setBranchQuantity(stockTmp.getBranch2());
            }
            
            if(store.endsWith("C")){
                stockDTO.setBranchQuantity(stockTmp.getBranch3());
            }
            
            this.stockList.add(stockDTO);
        }
    }
    
    
    
    


}
